"use client";
import {useMemo,useState} from "react";
type Vehiculo={patente:string;tipo:string;funcion:string;encargado:string;marca:string;modelo:string;ano:number;condicion:"Definitivo"|"Reemplazo"};
const flota:Vehiculo[]=[
["SPTV 18","Camioneta doble cabina","Supervisión","Nicolás Burgos","Dongfeng","New Rich DF6 MT 4x4",2026,"Definitivo"],
["TYYB 70","Camión liviano doble cabina","Apoyo de supervisión","Camila Villavicencio","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 71","Camión liviano doble cabina","Apoyo de supervisión","Nicolás Parada","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["SPBB 90","Camioneta doble cabina","Inspección técnica","Daoga","Dongfeng","New Rich DF6 MT 4x4",2026,"Definitivo"],
["TYYB 66","Camión liviano doble cabina","Manejo de arbolado","Nicolás Pérez","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 91","Camión liviano doble cabina","Aseo y jardinería","Natali González","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 85","Camión liviano doble cabina","Aseo y jardinería","Maritza Miranda","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 68","Camión liviano doble cabina","Aseo y jardinería","Gladys Carrillo","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 88","Camión liviano doble cabina","Aseo y jardinería","Alejandro Catalán","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["TYYB 76","Camión liviano doble cabina","Infraestructura","Rolando Serrano","Foton","TM5 DCAB 1.6",2026,"Definitivo"],
["PSJR 38","Camión recolector","Recolección de excedentes","Luis Cornejo","Volkswagen","Delivery",2021,"Definitivo"],
["RCLV 18","Camión recolector","Reemplazo por falla mecánica","Luis Cornejo","Por confirmar","Por confirmar",2021,"Reemplazo"],
["RGGG 31","Camión recolector","Recolección de excedentes","Manuel Sepúlveda","Hino","XZU 917",2022,"Definitivo"],
["VBCT 57","Camión tolva","Transporte de áridos","Manuel Rodríguez","JAC","Runner HFC",2026,"Definitivo"],
["RGCB 37","Camión capacho","Podas en altura","Manuel Valenzuela","Volkswagen","Delivery 9170",2022,"Definitivo"],
["VCTP 91","Camión aljibe","Apoyo al riego","Fidel Castro","Hino","FG 1728",2026,"Definitivo"],
["VCSV 80","Camión aljibe","Apoyo al riego","Nicolás Olguín","Hino","FG 1728",2026,"Definitivo"],
["TZVJ 84","Minicargador","Apoyo a construcción y podas","Carlos González","Bobcat","S590",2026,"Definitivo"]
].map(v=>({patente:v[0],tipo:v[1],funcion:v[2],encargado:v[3],marca:v[4],modelo:v[5],ano:v[6],condicion:v[7]} as Vehiculo));
const docs=["Permiso de circulación","SOAP","Revisión técnica","Certificado de gases"];
export default function Home(){const[consulta,setConsulta]=useState("");const[tipo,setTipo]=useState("Todos");const[seleccion,setSeleccion]=useState(flota[0].patente);const[vista,setVista]=useState<"flota"|"documentos">("flota");const tipos=useMemo(()=>["Todos",...new Set(flota.map(v=>v.tipo))],[]);const visibles=flota.filter(v=>(tipo==="Todos"||v.tipo===tipo)&&`${v.patente} ${v.encargado} ${v.funcion}`.toLowerCase().includes(consulta.toLowerCase()));const activo=flota.find(v=>v.patente===seleccion)||visibles[0]||flota[0];return <main>
<header className="hero"><div className="top"><div className="marca"><b>M6</b><span><strong>Maipú</strong><small>Zona 6 · Gestión operacional</small></span></div><small>Maqueta inicial · Informe junio 2026</small></div><div className="heroTexto"><p>CONTROL DOCUMENTAL Y OPERATIVO</p><h1>Gestión de<br/><em>flota</em></h1><span>Una vista única para identificar vehículos, responsables y documentación que requiere atención.</span></div><aside><small>Flota informada</small><strong>{flota.length}</strong><span>vehículos y maquinarias</span></aside></header>
<nav><button className={vista==="flota"?"activo":""} onClick={()=>setVista("flota")}>Panel de flota</button><button className={vista==="documentos"?"activo":""} onClick={()=>setVista("documentos")}>Control documental</button></nav>
<section className="filtros"><div><span>Vista operativa</span><strong>{visibles.length} registros visibles</strong></div><label>Tipo de vehículo<select value={tipo} onChange={e=>setTipo(e.target.value)}>{tipos.map(t=><option key={t}>{t}</option>)}</select></label><label>Buscar por patente o responsable<input value={consulta} onChange={e=>setConsulta(e.target.value)} placeholder="Ej.: TYYB 70 o Camila"/></label></section>
{vista==="flota"?<><section className="kpis"><article><span>UNIDADES REGISTRADAS</span><strong>{flota.length}</strong></article><article><span>VEHÍCULOS DEFINITIVOS</span><strong>17</strong></article><article><span>REEMPLAZOS ACTIVOS</span><strong>1</strong></article><article><span>DOCUMENTOS POR CARGAR</span><strong>72</strong></article></section><section className="trabajo"><article className="panel listado"><header><div><span>INVENTARIO</span><h2>Vehículos y maquinarias</h2></div><small>Selecciona una patente</small></header><div className="tabla"><div className="fila titulos"><span>Patente</span><span>Tipo</span><span>Responsable</span><span>Condición</span></div>{visibles.map(v=><button className={`fila ${activo.patente===v.patente?"sel":""}`} key={v.patente} onClick={()=>setSeleccion(v.patente)}><strong>{v.patente}</strong><span>{v.tipo}</span><span>{v.encargado}</span><b className={v.condicion==="Reemplazo"?"reemplazo":""}>{v.condicion}</b></button>)}</div></article><aside className="panel ficha"><div className="patente"><small>PATENTE</small><strong>{activo.patente}</strong></div><span>FICHA OPERATIVA</span><h2>{activo.funcion}</h2><dl><div><dt>Responsable</dt><dd>{activo.encargado}</dd></div><div><dt>Tipo</dt><dd>{activo.tipo}</dd></div><div><dt>Marca y modelo</dt><dd>{activo.marca} · {activo.modelo}</dd></div><div><dt>Año</dt><dd>{activo.ano}</dd></div></dl><button onClick={()=>setVista("documentos")}>Revisar documentos →</button></aside></section></>:<section className="documental"><article className="aviso"><div><span>PRIMERA BRECHA DETECTADA</span><h2>Las fechas deben transformarse en datos</h2><p>El informe contiene imágenes de documentos, pero no una tabla confiable de vencimientos. Esta maqueta no inventa fechas.</p></div><strong>72<small>fechas por cargar</small></strong></article><section className="docs"><aside className="panel selector">{flota.map(v=><button className={activo.patente===v.patente?"sel":""} key={v.patente} onClick={()=>setSeleccion(v.patente)}><strong>{v.patente}</strong><span>{v.funcion}</span></button>)}</aside><article className="panel carpeta"><header><div><span>CARPETA DOCUMENTAL</span><h2>{activo.patente} · {activo.encargado}</h2></div><small>4 documentos esenciales</small></header>{docs.map(d=><div className="doc" key={d}><i/><div><strong>{d}</strong><span>Fecha de vencimiento aún no cargada</span></div><b>Fecha pendiente</b></div>)}</article></section></section>}
<footer><span>Fuente inicial: Flota Zona 6 · junio 2026</span><span>Tablero independiente · sin datos de Provisiones</span></footer></main>}
