"use client";
import {useMemo,useState} from "react";
type Vehiculo={numero:string;categoria:string;tipo:string;encargado:string;patente:string;marca:string;modelo:string;año:number};type Exigencia={categoria:string;etiqueta:string;icono:"pickup"|"carrozado"|"recolector"|"tolva"|"grua"|"aljibe"|"bobcat";base:number;actual:number};
const flota:Vehiculo[]=[
{numero:"1",categoria:"supervisor",tipo:"Vehículo Supervisor",encargado:"Nicolás Burgos",patente:"SPTV 18",marca:"Dongfeng",modelo:"New Rich DF6 MT 4x4",año:2025},
{numero:"2",categoria:"ayudante",tipo:"Vehículo Ayudante Supervisor",encargado:"Camila Villavicencio",patente:"TYYB 70",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"3",categoria:"ayudante",tipo:"Vehículo Ayudante Supervisor",encargado:"Nicolás Parada",patente:"TYYB 71",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"4",categoria:"its",tipo:"Vehículo ITS",encargado:"Daoga - Inspección Técnica",patente:"SPBB 90",marca:"Dongfeng",modelo:"New Rich DF6 MT 4x4",año:2025},
{numero:"5",categoria:"arbolado",tipo:"Vehículo Equipo de Manejo Arbolado",encargado:"Nicolás Pérez",patente:"TYYB 66",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"6",categoria:"dotacion",tipo:"Vehículo Dotación de Equipo",encargado:"Natali González",patente:"TYYB 91",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"7",categoria:"dotacion",tipo:"Vehículo Dotación de Equipo",encargado:"Maritza Miranda",patente:"TYYB 85",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"8",categoria:"dotacion",tipo:"Vehículo Dotación de Equipo",encargado:"Gladys Carrillo",patente:"TYYB 68",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"9",categoria:"dotacion",tipo:"Vehículo Dotación de Equipo",encargado:"Alejandro Catalán Morales",patente:"TYYB 88",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"10",categoria:"infraestructura",tipo:"Vehículo Infraestructura",encargado:"Rolando Serrano",patente:"TYYB 76",marca:"Foton",modelo:"TM5 DCA B 1.6",año:2025},
{numero:"11",categoria:"recolector",tipo:"Vehículo Recolector",encargado:"Manuel Sepúlveda Hormazábal",patente:"RGGG 31",marca:"Hino",modelo:"XZU 917",año:2022},
{numero:"12",categoria:"recolector",tipo:"Vehículo Recolector",encargado:"Luis Cornejo",patente:"PSJR 38",marca:"Volkswagen",modelo:"Delivery 9170",año:2023},
{numero:"13",categoria:"aridos",tipo:"Vehículo de Transporte de Áridos",encargado:"Manuel Rodríguez",patente:"VBCT 57",marca:"JAC",modelo:"Runner HFC",año:2025},
{numero:"14.A",categoria:"podas",tipo:"Vehículo de Podas en Altura",encargado:"Manuel Valenzuela",patente:"RGCB 37",marca:"Volkswagen",modelo:"Delivery 9170",año:2022},
{numero:"15",categoria:"aljibe",tipo:"Camión Aljibe Apoyo al Riego",encargado:"Fidel Castro",patente:"VCTP 91",marca:"Hino",modelo:"FG 1728",año:2025},
{numero:"16",categoria:"aljibe",tipo:"Camión Aljibe Apoyo al Riego",encargado:"Nicolás Olguín",patente:"VCSV 80",marca:"Hino",modelo:"FG 1728",año:2025},
{numero:"17",categoria:"minicargador",tipo:"Mini Cargador",encargado:"Carlos González",patente:"TZVJ 84",marca:"Bobcat",modelo:"S590",año:2025}];
const exigencias:Exigencia[]=[{categoria:"supervisor",etiqueta:"Supervisión",icono:"pickup",base:1,actual:1},{categoria:"ayudante",etiqueta:"Ayudantes de supervisor",icono:"carrozado",base:2,actual:2},{categoria:"its",etiqueta:"Inspección técnica ITS",icono:"pickup",base:1,actual:1},{categoria:"arbolado",etiqueta:"Manejo de arbolado",icono:"carrozado",base:1,actual:1},{categoria:"dotacion",etiqueta:"Dotación de equipo",icono:"carrozado",base:4,actual:4},{categoria:"infraestructura",etiqueta:"Infraestructura",icono:"carrozado",base:1,actual:1},{categoria:"recolector",etiqueta:"Recolectores",icono:"recolector",base:2,actual:2},{categoria:"aridos",etiqueta:"Transporte de áridos",icono:"tolva",base:1,actual:1},{categoria:"podas",etiqueta:"Podas en altura · 10 m mín.",icono:"grua",base:1,actual:1},{categoria:"aljibe",etiqueta:"Camiones aljibe",icono:"aljibe",base:2,actual:2},{categoria:"minicargador",etiqueta:"Minicargador",icono:"bobcat",base:1,actual:1}];
function VehiculoIcono({tipo}:{tipo:Exigencia["icono"]}){return <span className={`vehiculoAprobado ${tipo}`}/>}
const documentos=["Permiso de circulación","SOAP","Revisión técnica","Certificado de gases","Cédula de identidad","Licencia de conducir"];const iniciales=(nombre:string)=>nombre.split(" ").filter(Boolean).map(parte=>parte[0]).slice(0,2).join("");
export default function Home(){const[consulta,setConsulta]=useState("");const[categoria,setCategoria]=useState("Todas");const[seleccion,setSeleccion]=useState(flota[0].patente);const[vista,setVista]=useState<"flota"|"documentos">("flota");const visibles=useMemo(()=>flota.filter(v=>(categoria==="Todas"||v.categoria===categoria)&&`${v.patente} ${v.encargado} ${v.tipo} ${v.marca}`.toLowerCase().includes(consulta.toLowerCase())),[categoria,consulta]);const activo=flota.find(v=>v.patente===seleccion)||visibles[0]||flota[0];return <main>
<header className="hero"><div className="top"><div className="marca"><b>M6</b><span><strong>Maipú</strong><small>Zona 6 · Gestión operacional</small></span></div><small>Actualización de flota · julio 2026</small></div><div className="heroTexto"><p>CONTROL CONTRACTUAL Y OPERATIVO</p><h1>Gestión de<br/><em>flota</em></h1><span>Vista rápida de los vehículos disponibles, sus funciones y responsables asignados.</span></div><aside><small>Flota disponible</small><strong>{flota.length}</strong><span>Dotación operativa informada</span></aside></header>
<nav><button className={vista==="flota"?"activo":""} onClick={()=>setVista("flota")}>Panel de flota</button><button className={vista==="documentos"?"activo":""} onClick={()=>setVista("documentos")}>Control documental</button></nav>
<section className="filtros"><div><span>Vista operativa</span><strong>{visibles.length} de {flota.length} registros visibles</strong></div><label>Función del vehículo<select value={categoria} onChange={e=>setCategoria(e.target.value)}><option value="Todas">Todas</option>{exigencias.map(item=><option key={item.categoria} value={item.categoria}>{item.etiqueta}</option>)}</select></label><label>Buscar por patente o responsable<input value={consulta} onChange={e=>setConsulta(e.target.value)} placeholder="Ej.: TYYB 70 o Camila"/></label></section>
{vista==="flota"?<><section className="tiposPanel"><div className="tiposCabecera"><div><span className="rotulo">TIPOS DE VEHÍCULOS</span><h2>Dotación por función</h2><p>Resumen visual de las 17 unidades operativas informadas.</p></div></div><div className="leyenda"><span><i className="base"/>Base técnica</span><span><i className="actual"/>Flota actual</span></div><div className="pictogramas">{exigencias.map(item=><article className={`pictograma ${item.actual>item.base?"conExtra":""}`} key={item.categoria}><div className="iconoVehiculo" aria-hidden="true"><VehiculoIcono tipo={item.icono}/></div><div className="pictogramaTexto"><strong>{item.etiqueta}</strong><div className="cantidadTipo"><b>{item.actual}</b><span>{item.actual===1?"vehículo":"vehículos"}</span></div></div></article>)}</div></section>
<section className="trabajo"><article className="panel listado"><header><div><span>INVENTARIO</span><h2>Vehículos y maquinarias ({visibles.length})</h2></div><small>Selecciona una patente</small></header><div className="tabla"><div className="fila titulos"><span>N°</span><span>Tipo de vehículo / maquinaria</span><span>Encargado</span><span>Patente</span><span>Marca</span><span>Modelo</span><span>Año</span></div>{visibles.map(v=><button className={`fila ${activo.patente===v.patente?"sel":""}`} key={v.patente} onClick={()=>setSeleccion(v.patente)}><b>{v.numero}</b><span>{v.tipo}</span><span>{v.encargado}</span><strong>{v.patente}</strong><span>{v.marca}</span><span>{v.modelo}</span><span>{v.año}</span></button>)}</div></article><aside className="panel ficha"><div className="patente"><small>PATENTE</small><strong>{activo.patente}</strong></div><span>FICHA TÉCNICA</span><h2>{activo.tipo}</h2><div className="conductor"><div className="fotoConductor">{iniciales(activo.encargado)}</div><div><small>CONDUCTOR ASIGNADO</small><strong>{activo.encargado}</strong><span>Licencia: clase por confirmar</span></div></div><dl><div><dt>Marca y modelo</dt><dd>{activo.marca} · {activo.modelo}</dd></div><div><dt>Año</dt><dd>{activo.año}</dd></div><div><dt>Licencia</dt><dd>Fecha pendiente</dd></div><div><dt>Cédula</dt><dd>Fecha pendiente</dd></div></dl><button onClick={()=>setVista("documentos")}>Revisar vencimientos →</button></aside></section></>:<section className="documental"><article className="aviso"><div><span>CONTROL DE VENCIMIENTOS</span><h2>Documentos esenciales por vehículo</h2><p>Las fechas se mantendrán pendientes hasta contar con una fuente maestra revisada. Los documentos personales no se publican en GitHub.</p></div><strong>{flota.length*documentos.length}<small>fechas por cargar</small></strong></article><section className="docs"><aside className="panel selector">{flota.map(v=><button className={activo.patente===v.patente?"sel":""} key={v.patente} onClick={()=>setSeleccion(v.patente)}><strong>{v.patente}</strong><span>{v.tipo}</span></button>)}</aside><article className="panel carpeta"><header><div><span>CARPETA DOCUMENTAL</span><h2>{activo.patente} · {activo.encargado}</h2></div><small>6 documentos esenciales</small></header>{documentos.map(d=><div className="doc" key={d}><i/><div><strong>{d}</strong><span>Fecha de vencimiento aún no cargada</span></div><b>Fecha pendiente</b></div>)}<button className="pdfProtegido" onClick={()=>window.alert("El PDF protegido se habilitará cuando se carguen los documentos privados.")}>Descargar informe protegido <span>PDF con contraseña →</span></button></article></section></section>}
<footer><span>Fuentes: Base técnica, tabla 12 · Flota Zona 6, julio 2026</span><span>Vista publicada · datos sujetos a revisión documental</span></footer></main>}
